name: backend-ci
on: [push, pull_request]
defaults: { run: { working-directory: backend } }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements_modern.txt
      - run: python manage.py migrate --noinput
      - run: echo "Smoke test OK"
  build-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          tags: backend-demo:ci
